server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wesquel/config-server
          #Private repository
          #username: username
          #password: password
          search-paths:
          - 'greeting-service*'
