spring:
  application:
    name: greeting-service
  output: 
    ansi: 
      enabled: ALWAYS
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Cia"
  value: "Mondo"