server:
  port: 8080
spring:
  application:
    name: greeting-service
  output: 
    ansi: 
      enabled: ALWAYS
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'